name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - "packages/auth/**"

defaults:
  run:
    working-directory: packages/auth

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://mfe-akp-bucket/auth/latest
        env:
          AWS_ACCESS_KEY_ID: AKIARNKFBZJCBAUHZYSZ
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: ap-northeast-1

      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/auth/latest/remoteEntry.js"
        env:
          AWS_ACCESS_KEY_ID: AKIARNKFBZJCBAUHZYSZ
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: ap-northeast-1
